'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "a", t = "aa"
Output: "a"
'''




class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        #set(t) generates a set of unique characters. Thus if t="aa", then set(t)={'a'}.
        return ''.join([i for i in set(t) if t.count(i)!=s.count(i)])
        '''
        Another Method (My solution)
        
        
        s1=Counter(s)
        s2=Counter(t)
        for i in s2:
            if s1[i]!=s2[i]:
                return i
        '''         
        '''
        This is my solution. But I wanted a faster solution.
        
        
        s1=list(s)
        t1=list(t)
        for i in t:
            if i in s1:
                t1.remove(i)
                s1.remove(i)
                
        return t1[0]
        '''
